name: Static WordPress to GH Pages
on:
  repository_dispatch:
    types: [wordpress]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install -r requirements.txt
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
           
      - name: Dump GitHub context
        env:
         GITHUB_CONTEXT: ${{ toJson(github.event.client_payload) }}
         GITHUB_CONTEXT2: ${{ toJson(github.event.client_payload.archive_name) }}
        
        run: python main.py -user ${{vars.user}} -token  ${{vars.token}} -src ${{vars.src}} -dst ${{vars.dst}}
